FujiNetWIFI/fujinet-firmware

tests/tnfsBoot/tnfsBoot.ino
Revert to original sio_get_command without skip, change debug prints so they look better in serial monitor, change offset order in seek to make it work. success!
=> tnfsBoot: make it work

tests/diskulator/diskulator.ino
Can now debug over TCP/6502 or debug_serial port.
Fixes some erroneous debug output getting sent to the SIO.
=> Network debug

.gitattributes, .gitignore, tests/README.md, tests/cache/data/.gitattributes, tests/cio3/data/.gitattributes, tests/cio4-poll/atari/loader/.gitattributes, tests/cio4-poll/data/.gitattributes, tests/config-test/data/.gitattributes, tests/config/data/.gitattributes
created a gitignore for os files and gitattributes for the atari binary files
added a readme to the tests folder.
=> Little bit of organisation

esp32/tests/config/config.ino, platformio/FujiNet/lib/sio/disk.cpp, platformio/FujiNet/lib/sio/disk.h, platformio/FujiNet/lib/sio/sio.cpp, platformio/FujiNet/lib/sio/sio.h, platformio/FujiNet/src/main.cpp
refactored sio to have an SIO bus and devices. Still only single device capable.
=> Sio devices

README.md
THis is just a tiny change to the readme to test webhooks into the discord server.
I added links back to AA and discord in case people come across this site in GH and want to reach back out to the devs.
=> added contact links for aa and new discord server to readme

platformio/FujiNet/lib/LinkedList-1.2.3/LinkedList.h, platformio/FujiNet/lib/sio/disk.h, platformio/FujiNet/lib/sio/sio.cpp, platformio/FujiNet/lib/sio/sio.h, platformio/FujiNet/src/main.cpp
Defined an sioBus class. Declared two disk objects and added them to the sioBus linked list. Only one disk is operational right now. Compiles and links. Not yet tested.
=> sioBus class

esp32/tests/multilator/multilator.ino
Add TEST_NAME define.
Fixup Pin setup
=> Make it work. UDP.begin() can only be called AFTER WiFi.begin().

esp32/tests/multilator-rev2/multilator-rev2.ino
Reverts FujiNetWIFI/atariwifi#46 Needs a bit more work to not clobber over 8266.
=> Revert "correct sio timing issues"

esp32/tests/multilator-rev2/multilator-rev2.ino
Sorry, but my last pull request introduced regression on ESP8266.
I'm convinced that the sleeps (delay T0 - T4) are normally not needed, but without them ESP8266 behaves wrongly.
=> revert last ESP8266 SIO changes

platformio/FujiNet/fuijnet.code-workspace, platformio/FujiNet/lib/sio/disk.cpp, platformio/FujiNet/lib/sio/disk.h, platformio/FujiNet/lib/sio/modem.cpp, platformio/FujiNet/lib/sio/printer.cpp, platformio/FujiNet/lib/sio/sio.cpp, platformio/FujiNet/lib/sio/sio.h, platformio/FujiNet/src/main.cpp
Incorporated basic command,read,write,status algorithms (no TNFS cache) and SIO behavior (ACK,NAK,COMPLETE,ERROR). Tested reading and writing from SPIFFS and TNFS.
=> Multi2 into PIO - simple progress

platformio/FujiNet/lib/sio/sio.cpp, platformio/FujiNet/lib/sio/sio.h, platformio/FujiNet/src/main.cpp
platformio: add sio voltage check for ESP32 so we don't get stuckwaiting for cmd frame if atari is poweroff. add network debug support. add wifi LED check
=> platformio: add sio voltage check for ESP32 so we don't get stuck

platformio/FujiNet/lib/TNFSlib/tnfs_imp.cpp, platformio/FujiNet/lib/TNFSlib/tnfs_imp.h, platformio/FujiNet/lib/sio/fuji.cpp
seem to not be able to open two TNFS directories for reading? Get error 0x0E
=> fixed some directory reading problems

platformio/FujiNet/lib/hardware/bluetooth.cpp, platformio/FujiNet/lib/hardware/bluetooth.h, platformio/FujiNet/lib/hardware/keys.cpp, platformio/FujiNet/lib/hardware/keys.h, platformio/FujiNet/lib/sio/sio.cpp, platformio/FujiNet/lib/sio/sio.h, platformio/FujiNet/partitions_fujinet.csv, platformio/FujiNet/platformio.ini, platformio/FujiNet/src/main.cpp
- added custom partition table with increased OTA partitions and decreased SPIFFS partition
- restored BOOT key long and short press detection
- restored SIO2BT mode
=> restore Bluetooth functionality

platformio/FujiNet/lib/hardware/keys.cpp, platformio/FujiNet/lib/hardware/keys.h, platformio/FujiNet/partitions_fujinet.csv, platformio/FujiNet/platformio.ini, platformio/FujiNet/src/main.cpp
Let's do it step by step.
I split the commit (restore Bluetooth).
Now I submit 2 commits, so you can easily cherry pick any of them (as they are independent).
This is a preparation for the 3-rd commit, which will follow if you positively verify the first two :)
=> Prepare4bt

platformio/FujiNet/lib/sio/fuji.cpp, platformio/FujiNet/lib/sio/fuji.h
=> add image rotate()

platformio/FujiNet/lib/sio/fuji.cpp
=> image_swap count backward

platformio/FujiNet/lib/TNFSlib/tnfs_imp.h, platformio/FujiNet/lib/sio/modem.cpp, platformio/FujiNet/lib/sio/modem.h, platformio/FujiNet/lib/sio/network.h, platformio/FujiNet/lib/sio/networkProtocolTCP.h, platformio/FujiNet/lib/sio/sio.cpp, platformio/FujiNet/lib/sio/sio.h, platformio/FujiNet/platformio.ini, platformio/FujiNet/src/main.cpp
-Add lot's of ifdefs so it gets closer to building
-Add example configs in platformio.ini for linux & win
=> platformio: esp8266 modifications

platformio/FujiNet/.gitignore, platformio/FujiNet/lib/TNFSlib/tnfs_imp.cpp, platformio/FujiNet/lib/sio/disk.cpp, platformio/FujiNet/lib/sio/disk.h
This was originally intended to be a new implementation of read cache.
Decided instead to reinforce the non-cached TNFS implementation, adding seek optimization. and wait a bit to think on a new caching implementation.
=> New read cache

platformio/FujiNet/lib/hardware/bluetooth.cpp, platformio/FujiNet/lib/hardware/bluetooth.h, platformio/FujiNet/lib/hardware/keys.cpp, platformio/FujiNet/lib/hardware/keys.h, platformio/FujiNet/lib/hardware/led.cpp, platformio/FujiNet/lib/hardware/led.h, platformio/FujiNet/lib/sio/fuji.cpp, platformio/FujiNet/lib/sio/sio.cpp, platformio/FujiNet/lib/sio/sio.h, platformio/FujiNet/src/main.cpp
handle key presses and LEDs in a central place
confirm short key presses with LED blinking
=> refactor key and led handling

platformio/FujiNet/fujinet.code-workspace, platformio/FujiNet/lib/hardware/fnSystem.cpp, platformio/FujiNet/lib/hardware/fnSystem.h, platformio/FujiNet/lib/sio/modem.cpp, platformio/FujiNet/lib/sio/modem.h, platformio/FujiNet/lib/sio/sio.cpp
And also removed accidental change to workspace file
=> cleanup on modem.cpp

platformio/FujiNet/data/www/index.html, platformio/FujiNet/include/atascii.h, platformio/FujiNet/include/version.h, platformio/FujiNet/lib/EdUrlParser/EdUrlParser.cpp, platformio/FujiNet/lib/http/httpService.cpp, platformio/FujiNet/lib/http/httpServiceParser.cpp, platformio/FujiNet/lib/printer-emulator/file_printer.cpp, platformio/FujiNet/lib/printer-emulator/file_printer.h, platformio/FujiNet/lib/printer-emulator/html_printer.cpp, platformio/FujiNet/lib/printer-emulator/printer_emulator.cpp, platformio/FujiNet/lib/printer-emulator/printer_emulator.h, platformio/FujiNet/lib/sam/sam.c, platformio/FujiNet/lib/sio/printer.cpp, platformio/FujiNet/lib/sio/printer.h, platformio/FujiNet/lib/sio/sio.h
Default printer changed to file_trim, which seems more useful than file_raw.
=> ASCII/HTML pages open directly; file printer variants exposed

platformio/FujiNet/lib/sio/disk.cpp, platformio/FujiNet/lib/sio/fuji.cpp, platformio/FujiNet/lib/sio/sio.h
to allow other devices to be D1:.
=> Add Status timeout wait for fujinet device,

platformio/FujiNet/lib/TNFSlib/tnfslib.cpp, platformio/FujiNet/lib/TNFSlib/tnfslib.h, platformio/FujiNet/lib/TNFSlib/tnfslibMountInfo.cpp, platformio/FujiNet/lib/TNFSlib/tnfslibMountInfo.h, platformio/FujiNet/lib/http/httpServiceParser.cpp, platformio/FujiNet/lib/sio/printer.h
Note that the following TNFS commands are not implemented in the current TNFSD code:
CHMOD
SIZE
FREE
=> tnfslib functions completed

platformio/FujiNet/data/www/index.html, platformio/FujiNet/data/www/selectedprinter.js, platformio/FujiNet/include/version.h, platformio/FujiNet/lib/config/config.cpp, platformio/FujiNet/lib/config/config.h, platformio/FujiNet/lib/http/httpService.cpp, platformio/FujiNet/lib/http/httpServiceConfigurator.cpp, platformio/FujiNet/lib/http/httpServiceConfigurator.h, platformio/FujiNet/lib/http/httpServiceParser.cpp, platformio/FujiNet/lib/sio/printer.cpp, platformio/FujiNet/lib/sio/printer.h, platformio/FujiNet/lib/sio/printerlist.cpp, platformio/FujiNet/lib/sio/printerlist.h, platformio/FujiNet/lib/sio/sio.cpp, platformio/FujiNet/lib/sio/sio.h, platformio/FujiNet/src/main.cpp
Needs clean up to have config.cpp work directly off printerlist.cpp instead of keeping its own data
=> global printerlist and ability to change printer port

platformio/FujiNet/lib/printer-emulator/svg_plotter.cpp
also changed T1020.BAS on printers.ATR to make work like i think i should
=> modify A1020 behavior and explicitly type cast

platformio/FujiNet/lib/sio/network.cpp, platformio/FujiNet/lib/sio/networkProtocolFTP.h
=> include file tweaks

config/src/diskulator.c, config/src/screen.c, config/src/screen.h
Please enter the commit message for your changes. Lines starting
=> fixed bugs with gui

include/version.h, lib/hardware/keys.cpp, lib/hardware/keys.h
Should be easier to enter a short keypress than before
=> Rewrote key handling logic

lib/device/sio/fuji.cpp
I tested in fujinet-pc, but don't have my actual Atari hardware up at the moment so would need someone to test on the actual hardware if possible.
Also - feel free to change how things are done or let me know better ways to do what I'm doing - I haven't done much C in the last 15 years so comments welcome.
=> Return the "basename()" of the mounted image

include/version.h, lib/bus/iwm/iwm.cpp, lib/bus/iwm/iwm.h
use polling SPI transaction to sample WRITE line and pace decoding using iwm_timer utility - all protected by disabled interrupts
=> Fix large write

data/BUILD_ATARI/www/index.html, data/BUILD_ATARI/www/select.js, data/BUILD_ATARI/www/settings.js, data/BUILD_ATARI/www/template.html, data/BUILD_ATARI/www/utils.js, lib/config/fnc_modem.cpp, lib/config/fnc_save.cpp, lib/http/httpService.cpp, lib/http/httpServiceConfigurator.cpp, lib/http/httpServiceConfigurator.h
Updated web server interface in ATARI.
=> Web Interface updated for ATARI

data/BUILD_ADAM/www/index.html, data/BUILD_ADAM/www/select.js, data/BUILD_ADAM/www/settings.js, data/BUILD_ADAM/www/utils.js, data/BUILD_APPLE/www/index.html, data/BUILD_APPLE/www/select.js, data/BUILD_APPLE/www/settings.js, data/BUILD_APPLE/www/utils.js, data/BUILD_ATARI/www/index.html, data/BUILD_CBM/www/index.html, data/BUILD_CBM/www/select.js, data/BUILD_CBM/www/settings.js, data/BUILD_CBM/www/utils.js, data/BUILD_LYNX/www/index.html, data/BUILD_LYNX/www/select.js, data/BUILD_LYNX/www/settings.js, data/BUILD_LYNX/www/utils.js, data/BUILD_RS232/www/index.html, data/BUILD_RS232/www/select.js, data/BUILD_RS232/www/settings.js, data/BUILD_RS232/www/utils.js
Copied web build to all other BUILD targets.
=> Copied new Atari Web UI to other BUILD_ devices

data/BUILD_APPLE/www/index.html
A quick fix to allow APPLE users to see the list again.
=> Harcode APPLE printer list until fixed

.github/workflows/platformio.ini.ADAM, .github/workflows/platformio.ini.APPLE, .github/workflows/platformio.ini.ATARI
Should fix the build issues with the previous push
=> Add github workflow changes to include additional python scripts

lib/network-protocol/Protocol.cpp
add translations for LF->CR and CRLF->CR
=> change behaviour of translation mode on Apple 2

lib/hardware/fnRMTstream.cpp, lib/hardware/fnRMTstream.h
the RMT device wrapped in a class including a new ISR for seamless streaming.
=> adding fnRMTstream device

lib/bus/iwm/iwm.cpp
Add handling of data packets that come with bad commands that also have data packets with them to avoid a crash. This also allows the unhandled commands + data to be logged.
=> [iwm] handle bad commands that also have data packets.

platformio-sample.ini
RC2014: add to platformio-sample.ini
=> RC2014: add to platformio-sample.ini

lib/device/rc2014/network.cpp, lib/device/rc2014/network.h
fix implementation of set_login and set_password for the network device.
=> rc2014: network: implement set login and password

lib/EdUrlParser/EdUrlParser.cpp, lib/EdUrlParser/EdUrlParser.h, lib/device/adamnet/network.cpp, lib/device/adamnet/network.h, lib/device/comlynx/network.cpp, lib/device/comlynx/network.h, lib/device/h89/network.cpp, lib/device/h89/network.h, lib/device/iec/network.cpp, lib/device/iwm/network.cpp, lib/device/iwm/network.h, lib/device/new/network.cpp, lib/device/new/network.h, lib/device/rc2014/network.cpp, lib/device/rc2014/network.h, lib/device/rs232/network.cpp, lib/device/rs232/network.h, lib/device/s100spi/network.cpp, lib/device/s100spi/network.h, lib/device/sio/network.cpp, lib/device/sio/network.h, lib/hardware/fnWiFi.cpp, lib/network-protocol/ProtocolParser.cpp, lib/network-protocol/ProtocolParser.h, lib/utils/string_utils.cpp, lib/utils/string_utils.h, lib/utils/utils.cpp, lib/utils/utils.h
If accepted this closes #620 
I've tested every board compiles, but I don't have real boards to upload to except on Atari.
I've tested all the protocols work except TEST and SMB, but testing the ones I did proves the new protocol factory works.
Example debug for various protocols:
```text
21:06:41.567 > sioNetwork::parseURL(N:SSH://192.168.1.85:22/)
21:06:41.567 > sioNetwork::parseURL transformed to (N:SSH://192.168.1.85:22/, SSH://192.168.1.85:22/)
21:06:41.568 > Parse and instantiate protocol: N:SSH://192.168.1.85:22/
21:06:41.569 > NetworkProtocol::ctor()
21:06:41.569 > NetworkProtocolSSH::NetworkProtocolSSH(0x3ffaff88,0x3ffaffb0,0x3ffaffd8)
21:06:41.570 > sioNetwork::open_protocol() - Protocol SSH opened.
21:06:41.570 > translation mode = 3NetworkProtocolSSH::open() - Opening session. …
```
=> FN-620 Create Protocol Factory

lib/device/rs232/network.cpp, lib/device/sio/network.cpp, lib/ftp/fnFTP.h, lib/http/httpService.cpp, lib/meatloaf/device/flash.h, lib/meatloaf/network/tnfs.cpp, lib/network-protocol/FTP.h, lib/printer-emulator/atari_1029.cpp, lib/printer-emulator/commodoremps803.cpp, lib/printer-emulator/epson_80.cpp, lib/printer-emulator/okimate_10.cpp, lib/sam/sam.c, lib/utils/cbuf.h
A couple of these are 'todo' comments, the author should look at it to determine the best fix.
=> cppcheck warnings fixed

lib/EdUrlParser/EdUrlParser.cpp, lib/EdUrlParser/EdUrlParser.h, lib/TNFSlib/tnfslibMountInfo.cpp, lib/config/fnConfig.h, lib/config/fnc_bt.cpp, lib/config/fnc_cpm.cpp, lib/config/fnc_wifi.cpp, lib/device/rs232/network.cpp, lib/device/rs232/printer.cpp, lib/device/rs232/printer.h, lib/encrypt/crypt.h, lib/fn_esp_http_client/fn_http_header.cpp, lib/fnjson/fnjson.h, lib/ftp/fnFTP.h, lib/meatloaf/cbm_media.h, lib/meatloaf/device/flash.cpp, lib/meatloaf/meat_io.h, lib/meatloaf/network/http.cpp, lib/meatloaf/network/http.h, lib/meatloaf/network/tnfs.cpp, lib/meatloaf/network/tnfs.h, lib/network-protocol/FS.h, lib/network-protocol/HTTP.h, lib/network-protocol/Protocol.h, lib/printer-emulator/pdf_printer.cpp
dangling pointers were being accessed
all cppcheck errors have been squashed, next up, warnings...
=> cppcheck errors fixed:

lib/device/cx16_i2c/disk.cpp, lib/device/sio/disk.cpp, lib/device/sio/fuji.cpp
Just some simple baud rate output when printing sio_process messages.
=> Add baud output to disk and sio debug

lib/media/atari/diskTypeAtx.cpp
I think this is pretty stable, reduces the skew errors a lot.
=> Implement simpler _wait_head_position

lib/device/rc2014/fuji.cpp, lib/device/rc2014/fuji.h
Implement the base64 encode/decode commands.
This has only been compile-tested.
=> RC2014: fuji: implement base64 commands

lib/device/rc2014/fuji.cpp, lib/device/rc2014/fuji.h
Implement the SHA1/SHA256/SHA512 commands.
This has only been compile-tested.
=> RC2014: fuji: implement hashing commands

lib/device/iwm/fuji.cpp, lib/device/mac/fuji.cpp
Fix the destination slot being same as source slot
=> Set destination slot to 2nd byte of payload for copy

lib/device/rc2014/fuji.cpp, lib/device/rc2014/network.h
=> RC2014: fix std::string compiler errors

.gitignore, build-platforms/build-all.sh, build.sh, upstream.sh
Enhancing build.sh - creates a results file for ./build.sh -a (build all) so you can easily see what is building and what is not building.
fixing build.sh- adding ignore files
fixing build.sh- adding ignore files and upstream
working on incorporating upstream.sh into master
working results file for build-all
=> enchancements to build.sh and to build-all.sh

lib/FileSystem/fnFS.cpp, lib/FileSystem/fnFsSD.cpp, lib/FileSystem/fnFsSPIFFS.cpp, lib/FileSystem/fnFsTNFSvfs.cpp, lib/TNFSlib/tnfslib.cpp, lib/device/sio/cassette.cpp, lib/device/sio/udpstream.cpp, lib/http/httpServiceConfigurator.cpp, lib/http/httpServiceParser.cpp, lib/printer-emulator/atari_1029.cpp, lib/printer-emulator/atari_825.cpp, lib/printer-emulator/atari_xdm121.cpp, lib/printer-emulator/atari_xmm801.cpp, lib/printer-emulator/epson_80.cpp, lib/printer-emulator/okimate_10.cpp, lib/printer-emulator/pdf_printer.cpp, lib/printer-emulator/png_printer.cpp, lib/printer-emulator/printer_emulator.cpp, lib/printer-emulator/svg_plotter.cpp, lib/tcpip/fnDNS.cpp, src/main.cpp
solves the Issue #699 for the ATARI platform (`build_platform = BUILD_ATARI`)
As I mainly develop and test for this platform I changed this code only.
=> [atari] removed the "#ifdef DEBUG" directives where not needed

build-platforms/platformio-fujinet-coco-devkitc.ini, platformio-sample.ini, platformio.common.ini
Add board target for the 8MB DEVKITC-VE to the Coco build
=> Add fujinet-coco-devkitc board to build

lib/TNFSlib/tnfslib.cpp
Before this commit, we were switching from TNFS_PROTOCOL_UNKNOWN to TNFS_PROTOCOL_TCP after successfully sending a message. If the reply didn't come back, we switched back to TNFS_PROTOCOL_UDP.
After this commit, we keep TNFS_PROTOCOL_UNKNOWN until there's a successful reply (when we switch to TNFS_PROTOCOL_TCP) or a failure (then we go to TNFS_PROTOCOL_UDP).
This is mostly a cleanup. There's one minor change in behaviour: after this commit, if the user provides _tcp. prefix and the TCP connection fails, client *won't* fallback to UDP, as it would before the commit.
=> Switch from TNFS_PROTOCOL_UNKNOWN to TCP or UDP after a transaction.

lib/utils/string_utils.cpp
The error was: variable-sized object may not be initialized
=> Fixed a clang error by initializing a variable separately from its declaration.

lib/device/drivewire/fuji.h
=> Added the necessary include so that strlcpy definition could be found on

lib/FileSystem/fnFsTNFS.cpp, lib/FileSystem/fnFsTNFS.h, lib/TNFSlib/tnfslib.cpp
This PR enables the session recovery in the TNFS lib. Before that, this feature was only active outside of the ESP_PLATFORM.
=> Enable session recovery in TNFS.

lib/device/adamnet/fuji.cpp
Previous format:
day,month,year,hour,min,sec
New format:
century, year,month,day,hour,min,sec
=> Adam GET_TIME now returns the same format as apple GET_TIME

.github/workflows/autobuild.yml, .github/workflows/platformio.release-ATARI-esp32-s3-wroom-1-n16r8.ini
Hi,
new autobuild wokflow for ESP32-S3;
=> add ESP32-S3-WROOM-1-N16R8 to autobuild workflow

fujinet_firmware_uploader.md, fujinet_firmware_uploader.py
added python script to find and upload offical releases and nightlies to connected fujinet devices, from the command line.
=> [fujinet] added a new python script to upload releases from cli

lib/bus/drivewire/drivewire.cpp, lib/bus/sio/sio.cpp, lib/bus/sio/sio.h, lib/device/drivewire/modem.h, lib/device/sio/modem.cpp, lib/device/sio/modem.h, lib/device/sio/pclink.cpp, src/main.cpp
=> [refactor] move uart from modem to bus.

lib/bus/drivewire/drivewire.cpp, lib/bus/drivewire/drivewire.h, lib/bus/drivewire/dwcom/fnDwCom.h, lib/device/drivewire/fuji.cpp, lib/device/drivewire/fuji.h
Added support for missing DriveWire commands
Moved to a state machine for processing DriveWire commands
Moved to a state machine for processing FujiNet commands
=> Adapted to OS-9

build-platforms/platformio-fujinet-coco-devkitc.ini, pico/coco/main.c
disable pull resistors on the Pico pin going to the NMI pin on the CoCo
=> [coco] Nmi fix

lib/device/iwm/network.cpp
When fujinet-lib was updated to support network unit for apple2, it increased the count value of bytes the command sends.
This change detects that increase to determine on an sp_read/write/status/control whether the network unit id is present.
=> Only set the network unit if the command count has a value sent by fujinet-lib that supports it

lib/device/adamnet/fuji.cpp, lib/device/adamnet/fuji.h, lib/device/comlynx/fuji.cpp, lib/device/comlynx/fuji.h, lib/device/cx16_i2c/fuji.cpp, lib/device/cx16_i2c/fuji.h, lib/device/drivewire/fuji.cpp, lib/device/drivewire/fuji.h, lib/device/h89/fuji.cpp, lib/device/h89/fuji.h, lib/device/iec/fuji.cpp, lib/device/iec/fuji.h, lib/device/iwm/fuji.cpp, lib/device/iwm/fuji.h, lib/device/mac/fuji.cpp, lib/device/mac/fuji.h, lib/device/new/fuji.cpp, lib/device/new/fuji.h, lib/device/rc2014/fuji.cpp, lib/device/rc2014/fuji.h, lib/device/rs232/fuji.cpp, lib/device/rs232/fuji.h, lib/device/s100spi/fuji.cpp, lib/device/s100spi/fuji.h, lib/http/httpService.cpp, lib/http/httpService.h, lib/http/mgHttpService.cpp
add set_slot_hostname to rest of platforms and remove Atari #ifdefs for web ui host management endpoints
=> [fuji] add set_slot_hostname to rest of platforms

fujinet_firmware_uploader.py
Adds a feature to fujinet_firmware_uploader.py to allow specifying firmware zip on the command line to make it easy to flash a zip that was sent from someone during development/debugging.
Also added a flag to specify which port/device to use so fujinet_firmware_uploader.py doesn't have to guess.
=> Allow specifying firmware zip on command line

fujinet_firmware_uploader.py
Allow specifying firmware zip on command line in fujinet_firmware_uploader.py
=> Pull in latest master to v1.5-rc

lib/bus/iwm/iwm.cpp, lib/bus/iwm/iwm.h
=> FNFW-875: [diskii] Switch track when drive is changed without turning motor off.

lib/bus/iwm/iwm.cpp
Fixes https://github.com/FujiNetWIFI/fujinet-firmware/issues/876
=> FNFW-876: [diskii] Don't try to decode sectors if none were captured

Makefile
Also makes it easier to build from within emacs: M-x compile ``make -k -C `git rb` ``
`git rb` is in my `.gitconfig` as:
```
[alias]
repobase = rev-parse --show-toplevel
rb = repobase
```
=> Top level Makefile to make building easier

lib/bus/iwm/iwm_ll.cpp
Since we don't support full track formatting yet, I had another idea to try to get around the RAM starvation that the PlatformIO v6.10.0 is causing. Instead of allocating enough to capture an entire track I reduced the size to be just enough to hold 1 sector. Seems to work fine.
=> Allocate Disk II write buffer large enough to hold only 1 sector

lib/bus/rs232/rs232.h, lib/device/rs232/printer.cpp, lib/printer-emulator/pdf_printer.cpp, src/main.cpp
Adds Printer subdevice to RS232 as sub-device 0x40.
=> Add printer for rs232

lib/bus/rs232/rs232.cpp, lib/bus/rs232/rs232.h, lib/config/fnConfig.h, lib/config/fnc_load.cpp, lib/config/fnc_save.cpp, lib/config/fnc_serial.cpp, lib/config/fnc_util.cpp
Implements #930 by adding an [RS232] section:
```
[RS232]
baud=9600
```
=> Implement 930 rs232 baud rate

components_pc/libsmb2/lib/md4c.c, components_pc/libssh/CompilerChecks.cmake, components_pc/libssh/src/legacy.c, components_pc/libssh/src/scp.c, fujinet_pc.cmake, lib/FileSystem/fnFileCache.cpp, lib/bus/iwm/iwm.cpp, lib/device/iwm/fuji.cpp, lib/device/iwm/modem.cpp, lib/encoding/hash.cpp, lib/hardware/fnDummyWiFi.cpp, lib/hardware/fnSystem.cpp, lib/http/mgHttpService.cpp, lib/media/apple/mediaTypeDO.h, lib/network-protocol/SMB.h, lib/network-protocol/TNFS.h, lib/printer-emulator/pdf_printer.cpp, lib/utils/string_utils.cpp, lib/utils/utils.cpp
This started as a clean up for the fn-pc builds on osx which were riddled with warnings and cmake issues and finally had an error. AFter cleaning them up with help, I ran the builds on linux to validate and fixed up some more issues.
Then building firmware exposed some crufty with the mbedis code and so that was fixed.
All platforms build with this (output is below), but please take a look at it before accepting!
=> FN-PC clean up and other fixes

lib/FileSystem/fnFileCache.cpp, lib/bus/iwm/iwm_ll.cpp, lib/device/rs232/modem.cpp, lib/device/rs232/network.h, lib/device/sio/fuji.cpp, lib/encoding/hash.cpp, lib/hardware/fnSystem.cpp, lib/hardware/fnSystemNet.cpp, lib/hardware/fnUART.cpp
Reverts FujiNetWIFI/fujinet-firmware#958
=> Revert "Fix various warnings"

lib/FileSystem/fnFileCache.cpp, lib/bus/iwm/iwm_ll.cpp, lib/device/rs232/modem.cpp, lib/device/rs232/network.h, lib/device/sio/fuji.cpp, lib/encoding/hash.cpp, lib/hardware/fnSystem.cpp, lib/hardware/fnSystemNet.cpp, lib/hardware/fnUART.cpp
This should be good this time. Opening as draft to hopefully stop it going in until approvers get a chance to test.
=> Fix various warnings again

.github/workflows/autobuild.yml, build.sh
Testing you should do:
* brand new environment with almost nothing installed, no pio in PATH, `build.sh` should tell you what packages are needed when you try to build
* brand new environment with required packages installed:
* `./build.sh -p APPLE`
* `./build.sh -s fujiapple-rev0 && ./build.sh -b`
=> Work harder to get a Python virtual environment.

build.sh
Not sure how the PR checks yesterday didn't fail this
=> Check for clang++ not g++ on Windows/MSYS2 with clang

lib/device/iec/fuji.cpp, lib/device/iec/fuji.h
add missing methods for grabbing local IP info.
Ensure text comes out as petscii for BASIC.
=> Improve iec basic interface

lib/hardware/fnWiFi.cpp
=> [fnWifi] fixes #1010 force channel bitmap to scan all wifi channels.
