FujiNetWIFI/fujinet-firmware

- esp32/tests/modem/modem.ino
Sometimes we are too slow and CMD goes HIGH before we've read all the bytes.
> esp32/tests/modem: always get 5 bytes during CMD instead of when pin is low

- .gitignore
- platformio/FujiNet/fuijnet.code-workspace
- platformio/FujiNet/lib/sio/printer.cpp
- platformio/FujiNet/lib/sio/printer.h
- platformio/FujiNet/src/main.cpp
Add fill lines at page eject. Do not overwrite when page full - ignore instead. Begin new document once old one is sent to browser. Ignore char<32. Add extra \\ so it displays in PDF.
> Printer cleanup.

- esp32/tests/SIO2BT/README.md
- esp32/tests/SIO2BT/SIO2BT.ino
Bluetooth with Fujinet
ESP32 can act as a Bluetooth transceiver. It supports Serial Port Profile (SPP) and can run as a master.
SIO devices are emulated by the SIO2BT Android app or RespeQt PC software (Windows/Linux/Mac).
Before connecting to the ESP32, devices have to paired. In Android - go to settings, search for Bluetooth devices and select "ATARI Fujinet". Then start the SIO2BT app, which will let you connect to the ESP32.
Pairing on the PC will result in a virtual serial port beeing created. Select this serial port in RespeQT settings and change handshake to "SIO2BT". Opening the port initiates a Bluetooth connection.
> add Bluetooth test

- esp32/tests/multilator-rev2/multilator-rev2.ino
If this breaks things, feel free to slap me, but it seems to work so far with tests.
> flip ack/nak behavior to ensure unimplemented commands immediately nak.

- esp32/tests/multilator-rev2/multilator-rev2.ino
I have finally tested SIO timing on ESP8266 and removed superfluous sleeps from the code.
While merging my changes to the latest code base I had to resolve conflicts and removed duplicated checking of the command frame checksum.
According SIO spec: if the checksum if not correct, the SIO device should ignore the command (instead of sending NAK).
Regarding High Speed handling:
- $3F is a request about device capabilities and is meant to be send to floppy drives only (for example there is a conflict with $3F command for poll type 1)
- the HIAS's high speed patch and FJC U1MB firmware maintain HS index values for SIO devices 
(for example: if D1 is accessed first time, its speed capabilities will be requested. The next time it will be accessed with that speed.
Should D2  be accessed, again …
> cleanup SIO for 8266 + adjust serial timeouts + update traces

- esp32/tests/multilator-rev2/multilator-rev2.ino
Added short and long (1s) press handling for the BOOT key:
Short press - no action at the moment. It could trigger disk swap.
Long press toggles working mode:
Fujinet SIO -> SIO over Bluetooth (SIO2BT) -> Fujinet SIO -> etc.
> add BOOT key handling

- esp32/tests/multilator-rev2/multilator-rev2.ino
My NodeMCU (ESP32) does not have LEDs connected to the pins specified in the sketch.
That's why I couldn't test the commit, but I guess it should work.
I think that the user shall get visual feedback, when the long press is detected.
> keep the SIO LED on all the time when doing Bluetooth

- esp32/tests/tcp/atari-cio-relocator/rel.s
- esp32/tests/tcp/atari-cio-relocator/reloc.c
Code and data reside within the region to be remapped.  We really don't
want the remapper ruining data within the segment do we?  Nope.
The example assembly file shows how to write assembly that works with
the remapper.
> Made the relocator smarter by allowing the programmer to specify where

- platformio/FujiNet/lib/sio/disk.cpp
- platformio/FujiNet/src/main.cpp
platformio/siodisk: do not process commands for a drive whose file pointer is null (disk not mounted)
> platformio/siodisk: do not process cmds for null disk

- platformio/FujiNet/lib/hardware/bluetooth.cpp
- platformio/FujiNet/lib/hardware/bluetooth.h
- platformio/FujiNet/lib/sio/disk.cpp
- platformio/FujiNet/lib/sio/disk.h
- platformio/FujiNet/lib/sio/sio.cpp
- platformio/FujiNet/lib/sio/sio.h
- platformio/FujiNet/platformio.ini
- platformio/FujiNet/src/main.cpp
Due to a bug in the Arduino libraries:
https://github.com/espressif/arduino-esp32/issues/2718
I introduced a workaround to let Bluetooth be available all the time.
With the long press we toggle between Fujinet and SIO2BT mode.
> add SIO2BT mode

- platformio/FujiNet/lib/sio/fuji.cpp
rotates through disk images pulling file pointer from the sioDisk objects instead of static ATR table. Does not update ATR table - yet.
> try rotate image again

- platformio/FujiNet/src/main.cpp
A small correction, so the short key presses work well with or without BLUETOOTH_SUPPORT defined
> correct short key press logic

- .gitignore
- platformio/FujiNet/lib/TNFSlib/tnfs_imp.cpp
- platformio/FujiNet/lib/sio/fuji.cpp
- platformio/FujiNet/platformio.ini
address issue #172 by adding a '/' to end of directory names sent to CONFIG for display and directory traversal by the user.
> append '/' to directory names sent to CONFIG

- platformio/FujiNet/fujinet_partitions_16MB.csv
- platformio/FujiNet/fujinet_partitions_4MB.csv
- platformio/FujiNet/platformio.ini
Introduced 2 partition configurations:
- 4MB (without OTA)
- 16MB (with OTA)
Both configurations support 576kB spiffs.
Changes in paltformio.ini :
- it uses now fujinet_partitions_4MB.csv
- Bluetooth is enabled
> change flash partitions to bring more space for 4MB hardware

- platformio/FujiNet/lib/hardware/bluetooth.cpp
- platformio/FujiNet/lib/hardware/bluetooth.h
- platformio/FujiNet/platformio.ini
- platformio/FujiNet/src/main.cpp
Now Bluetooth is started only on demand (long key pressed), so there is no shortage of resources needed for other components.
Drawback:
BT restart (3 x long key press) causes a crash and reboot, so it is recommended to apply a fix to the file:
`esp32-hal-bt.c`
located at:
`path_to_user_data\.platformio\packages\framework-arduinoespressif32\cores\esp32`
as described here:
https://github.com/espressif/arduino-esp32/issues/2718#issuecomment-552213656
This is the corrected version of the btStop() method:
```
bool btStop(){
if(esp_bt_controller_get_status() == ESP_BT_CONTROLLER_STATUS_IDLE){
return true;
}
if(esp_bt_controller_get_status() == ESP_BT_CONTROLLER_STATUS_ENABLED){
if (esp_bt_controller_disable()) {
log_e("BT Disable failed");
return false;
}
while(esp_bt_controller_get_status() == …
```
> Bluetooth rework

- platformio/FujiNet/lib/TNFSlib/tnfslib.cpp
- platformio/FujiNet/lib/TNFSlib/tnfslib.h
- platformio/FujiNet/lib/config/config.cpp
Previous behavior: look for fnconfig.ini on SPIFFS and only make a copy from SD if none found.
New behavior: always copy fnconfig.ini from SD if found, then try to read what we have on SPIFFS.
> change fnconfig.ini read behavior to favor SD

- platformio/FujiNet/lib/FileSystem/fnFS.cpp
- platformio/FujiNet/lib/FileSystem/fnFS.h
- platformio/FujiNet/lib/FileSystem/fnFsSD.h
- platformio/FujiNet/lib/FileSystem/fnFsSPIF.h
- platformio/FujiNet/lib/FileSystem/fnFsTNFS.h
- platformio/FujiNet/lib/http/httpService.cpp
- platformio/FujiNet/lib/http/httpServiceConfigurator.cpp
- platformio/FujiNet/lib/http/httpServiceParser.cpp
- platformio/FujiNet/lib/printer-emulator/atari_1027.h
- platformio/FujiNet/lib/printer-emulator/atari_820.cpp
- platformio/FujiNet/lib/printer-emulator/atari_820.h
- platformio/FujiNet/lib/printer-emulator/atari_822.cpp
- platformio/FujiNet/lib/printer-emulator/atari_822.h
- platformio/FujiNet/lib/printer-emulator/pdf_printer.h
- platformio/FujiNet/lib/sio/printer.cpp
- platformio/FujiNet/lib/sio/printer.h
- platformio/FujiNet/lib/sio/sio.cpp
- platformio/FujiNet/lib/sio/sio.h
- platformio/FujiNet/src/main.cpp
- Moved Atari820 and Atari822 into separate files to match the rest of the printer_emu classes
- Removed sioPrinter::set_storage() in favor of forcing storage specification during sioPrinter construction (so we're not needlessly re-creating the output file).
- Removed global sioPrinter object in favor of creating a new instance dynamically at startup
- Changed some variable names for consistency/readabilty
> global sioPrinter relaced with dynamically-allocated object

- platformio/FujiNet/lib/printer-emulator/atari_825.cpp
- platformio/FujiNet/lib/printer-emulator/atari_825.h
Fixed logic error in dot spacing which caused the wrong font to be selected (proportional text was mistakenly underlined) when using Atari Writer.
> Atari 825 - dot spacing

- platformio/FujiNet/lib/printer-emulator/atari_825.cpp
- platformio/FujiNet/lib/printer-emulator/atari_825.h
implemented proper command/arg format for Atari 825 backspace mode. Corrected pdf_X coordinate updating for dot spacing and backspacing. Tested with some BASIC demo commands from manual
> Atari 825 backspace mode corrected

- include/version.h
- lib/hardware/fnWiFi.cpp
- lib/sio/apetime.cpp
- lib/sio/apetime.h
- lib/sio/disk.cpp
- lib/sio/disk.h
- lib/sio/fuji.cpp
- lib/sio/fuji.h
- lib/sio/modem.cpp
- lib/sio/modem.h
- lib/sio/network.cpp
- lib/sio/network.h
- lib/sio/printer.cpp
- lib/sio/printer.h
- lib/sio/sio.cpp
- lib/sio/sio.h
- lib/sio/voice.cpp
- lib/sio/voice.h
Allows for rebooting Atari for testing and reload CONFIG as long as no MOUNT commands are executed.
> Config boot ATR is now unloaded only when A8 sends MOUNT command

- lib/sio/fuji.h
A simple way for the A8 to store a block of data (up to 64 bytes) on SD.  Need to set up a test program for this.
> Fix appkey struct alignment

- lib/sio/modem.cpp
In sioModem::at_handle_dial() of modem.cpp, trim the host string. That way, users can enter AT dial commands, such as ATDT, with
one or more spaces before the hostname. Prior to this change, only no spaces were allowed. No spaces between AT and host still work. However, many term programs assume at least one space between the AT command and hostname.
> Allow spaces after AT command

- lib/sio/modem.cpp
In sioModem::sio_poll_1(), double the delay so there's plenty of time to load R: handler for stock machines and machines that support HSIO.
> Double delay time in sioModem::sio_poll_1()

- boards/fujinet-v1-8mb.json
- fujinet_partitions_8MB.csv
- platformio-sample - Copy.ini
Adding a build option and partition map for a WROVER module with 8MB flash (e.g. the official devkit C boards from Espressif)
> Add 8MB flash board

- lib/config/fnConfig.cpp
- lib/config/fnConfig.h
Proposed improvement for fnconfig.ini handling behaviour
1) fix issue causing fnconfig being copied from sd to spiffs every reset/reboot.
2) add new behaviour where fnconfig.ini being saved only on SD controled with [general] config field fnconfig_on_spifs=[1|0] /where 1 is default, to keep original functionality on.
0 will simply switch config read/write to only SD mode.
> fnconfig.ini handler fixes

- lib/config/fnConfig.cpp
This is workaround for bug causing SD is not being accessible when SIO2BT being enabled.
in case fnconfig_on_spiffs=0 that was causing crash.
> fix config write failure related crash

- data/www/index.html
- data/www/settings.js
- lib/config/fnConfig.cpp
- lib/config/fnConfig.h
- lib/http/httpServiceConfigurator.cpp
- lib/http/httpServiceConfigurator.h
- lib/http/httpServiceParser.cpp
- lib/sio/fuji.cpp
- lib/sio/fuji.h
- lib/sio/sio.cpp
By default FujiNet when config disk is mounted on DF1 will wait for 5 status commands (status_wait_count) before replying to allow real devices to reply first.
However this make FujiNet incompatible with SpartaDOS X , that not sent status_wait but starts reading directly from DF1.
That was causing autorun.atr (config disk) being automagically ejected.
In this commit i implemented new flag in general section, that by default is set to 1 (to keep original functionality on)
if User set this flag to 0 , fujinet will not wait 5 status commands, which will allow to boot spartados and call config.com from there.
Second Commit implement proposed WebGui switch allowing alter general/status_wait_enabled flag.
Probably webgui message need to be slightly altered to make it more readable to …
> Add general/status_wait_enabled (default true).

- lib/sio/modem.cpp
This is accomplished by emitting a connect message when ATDT5551234 is sent.  We need to do a separate connect message here since we want to preserve command mode.  Otherwise, the follow-up ATDT command by the Bobterm macro would not work.
> Restore ATDT5551234 functionality

- lib/bus/adamnet/adamnet.cpp
- lib/bus/sio/sio.cpp
- lib/device/adamnet/modem.cpp
- lib/device/sio/midimaze.cpp
- lib/device/sio/modem.cpp
- lib/hardware/fnBluetooth.cpp
- lib/runcpm/abstraction_fujinet.h
use of fnUartSIO.available() returns -1 on error
> use of fnUartSIO.available() didn't take error result into account

- lib/fnjson/fnjson.cpp
(*) [fnjson] if numeric value with fraction returns as 10 digit double, otherwise returns 64 bit integer
(*) refactoring - [fnjson] uses getter method instead of directly accessing fields 
(+) optimizing [fnjson] print debugging output when getting JSON values
> fixes #512

- lib/device/sio/network.cpp
- lib/fnjson/fnjson.cpp
- lib/fnjson/fnjson.h
#514 
Now the JSON Query routine can convert UTF-8 special characters to ATARI compatible ones. You (the user) can control the conversion via SIO AUX2 when issuing the "Q" command. The lowest two bits decide what to do.
Bit 0=0 - no conversion at all
Bit 0=1 - conversion dependent on Bit 1
Bit 1=0 - conversion of the common latin diacritics (á, à, é etc.) by stripping the accent (á and à to a etc.) and German umlauts (ä, ö, ü, ß etc.) to the two letter transcription (ä to ae, ß to ss etc.)
Bit 1=1 - conversion of all characters contained in the ATASCII international character set (see [Wikipedia](https://en.wikipedia.org/wiki/ATASCII#International_Character_Set))
Example in BASIC: Call until now:
`XIO ASC("Q"),#1,12,0,"N:/path/to/string/element"` and an UTF-8 **ä** will be garbage
Change …
> Json stuff

- lib/bus/iwm/iwm.cpp
- lib/bus/iwm/iwm.h
- lib/device/iwm/clock.cpp
- lib/device/iwm/clock.h
- lib/device/iwm/fuji.cpp
- lib/device/iwm/fuji.h
This PR adds RTC support for the Apple II. 
There is a new device on the Smartport bus. The new device responds to the common status code plus two more 'T' and 'P'.
'T' returns the current date and time on separate bytes, easy for any program to use.
'P' response is four packet bytes long with the format ProDOS uses internally and on the GetTime command. This is done to simplify the device driver.
Once this PR is complete, I will do a PR upstream for the ProDOS device driver, meanwhile the code for the driver is in https://github.com/ivanizag/prodos-drivers/tree/main/fujinet
> Real time clock support for the Apple II

- build_webui.py
Tested on windows and linux now.
jinja requires '/' in its paths, but when you're writing the data back out, you need backslashes on windows, so a combination of the two types of slashes are needed to get it working. hey ho.
> build_webui.py: Use os.path.join in place of hardcoded slashes

- lib/bus/iwm/iwm.cpp
- lib/bus/iwm/iwm.h
- lib/device/iwm/disk.cpp
- lib/device/iwm/disk.h
- lib/device/iwm/fuji.cpp
- lib/http/httpService.cpp
This is an experimental implementation of support for the eject command, 
disk switched status and treating read only mounted disks as proper write protected disks.  
You should be able to swap out disks during the System 6.0.1 install process with this installed.
> Implement eject command, disk switched status reporting and write protected status reporting.

- lib/bus/iwm/iwm.cpp
- lib/device/iwm/disk.cpp
Change iwm so that inactive devices can still report back status/reply to init requests, this is important for removable media because
eject is removing the disk from the drive, not yanking the drive from the bus. 
this also fixes a problem where I was leaking memory when mounting a new disk on top of an already active slot
because I wasn't fully calling _disk->unmount() before destroying the _disk object and continuing with the mount process.
> Eject improvements

- lib/device/iwm/network.cpp
Previous to this patch, the fujinet would always return 512 bytes of data, regardless as to what was requested.
> This change makes the smartport respect the number of bytes requested

- lib/network-protocol/FS.cpp
For now, revert back to 512 bytes waiting for the Atari while I try to solve the binary loader to handle unlimited bytes waiting.
> Reverted max bytes waiting to 512 for ATARI build

- lib/http/httpService.cpp
- src/main.cpp
This addresses two issues that kept me from doing a full test run of installing gsos from scratch, verifying it and adding extra applications on top while doing many disk swaps from the web UI on a single boot of the fujinet.  
the two problems encountered were: 
- webUI: memory leak that lead to sdmmc errors after enough file navigation was done.
- interrupts allowed in both CPU cores leading to watchdog timeouts obtaining locks held in the opposite core.
> Reliability fixes

- lib/bus/iwm/iwm.cpp
- lib/bus/iwm/iwm.h
- lib/device/iwm/disk.cpp
- lib/device/iwm/fuji.cpp
- lib/device/iwm/fuji.h
- lib/http/httpService.cpp
This PR changes disk switched behavior to be more like what I've observed using a real  800k floppy drive. it's much less aggressive at returning offline status on reads, clears switched status earlier but still has some protections in place.  
The one place we don't follow strictly the ApleDisk 3.5 firmware driver behavior is that we check for reading  blocks > 2 when switched = true and if so report offline status and clear switched.  this is to protect reads from the wrong disk being written somewhere and is mainly paranoia on my part. 
if blocks 0 , 1 or 2 are read it clears switched condition and allows the reads for any block on the disk from that point forward. this should keep ProDOS happy, older Installer programs like the ORCA/M installer that don't poll status but read block 2 …
> remove eject_latch code and try to mimic AppleDisk 3.5 status behavior.

- lib/bus/iwm/iwm.h
- lib/device/iwm/disk.cpp
prevent device types changing when finder re-starts if the device happens to have been offline. sometimes the finder cares not only about the volume name but also the type.
We also re-locate the error condition tests in iwm_readblock until after we get our block number so debug messages are easier to reason about.
> [iwm] [disk] remember previous type byte when offline.

- lib/device/iwm/cpm.cpp
- lib/device/iwm/modem.cpp
- lib/device/iwm/modem.h
interesting, for read calls, SP supports returning only what it has available for a read. It puts the actual number of bytes returned in X & Y. Works for Liron and softsp. I have not tested in the IIc+, but it may not work there. I'm using this for A3 support as one mode of the standard terminals uses this ask for a lot of bytes, and accept just what is available approach. So only using read calls to poll for data.
> add open/close and update read handling for cpm & modem (a3)

- README_wifi.md
- lib/config/fnConfig.cpp
- lib/config/fnConfig.h
- lib/config/fnc_general.cpp
- lib/config/fnc_load.cpp
- lib/config/fnc_save.cpp
- lib/config/fnc_util.cpp
- lib/config/fnc_wifi.cpp
- lib/device/sio/fuji.cpp
- lib/encrypt/crypt.h
- lib/hardware/fnWiFi.cpp
- lib/hardware/fnWiFi.h
- lib/hardware/keys.cpp
This fixes #493
The fuji will attempt to connect to the currently configured wifi, and if that fails will attempt to match any networks against stored entries, and try them in order of saved config which means it will try the last one it was able to connect to first if more than one network is found.
This means if you're constantly in range of multiple devices, you can't currently pick the second one without removing the entry for the other. This could be a future enhancement if needed.
Note it will only attempt to connect to something that is visible from a network scan and ignore other saved entries (which massively speeds up the process of connecting to one of the stored entries).
For new networks, as they are added, old networks are pushed down the 'stack' of old wifi configs until a …
> Add multiple wifi slots

- lib/bus/iwm/iwm_ll.cpp
Sometimes on GS/OS shutdown or switching betwen ProDOS and GS/OS a control code 0 data packet gets sent with garbage and a bad checksum.
This patch accepts bad data packets when the last recieved command is a control command with code 0.
> [iwm] ignore bad data packets on control code 0

- lib/bus/rc2014bus/rc2014bus.h
- lib/device/rc2014/printer.h
- lib/device/rc2014/rc2014cpm.h
The update to platformio ESP32 platform causes a couple of new compiling issues. Fix them.
> rc2014: build: update to platformio esp platform 6.1

- lib/device/comlynx/udpstream.cpp
- lib/device/cx16_i2c/printer.cpp
- lib/device/drivewire/cassette.cpp
- lib/device/drivewire/clock.cpp
- lib/device/drivewire/fuji.cpp
- lib/device/drivewire/network.cpp
- lib/device/drivewire/printer.cpp
- lib/device/iwm/clock.cpp
- lib/device/iwm/cpm.cpp
- lib/device/iwm/network.cpp
- lib/device/rs232/apetime.cpp
- lib/device/rs232/disk.cpp
- lib/device/rs232/fuji.cpp
- lib/device/rs232/modem.cpp
- lib/device/rs232/network.cpp
- lib/device/rs232/printer.cpp
- lib/device/rs232/printerlist.cpp
- lib/device/rs232/rs232cpm.cpp
lib/device/drivewire had an incorrect ifdef to ATARI still for cassette code, causing it to be picked over sio.
other BUILD_ comments also fixed.
> Fix BUILD_COCO ifdef and other BUILD_ comments

- lib/runcpm/abstraction_fujinet.h
- lib/runcpm/abstraction_fujinet_apple2.h
- lib/tcpip/fnTcpServer.cpp
- lib/tcpip/fnTcpServer.h
Clean up error handling of tcpServer().begin
> Add return value for tcpServer.begin() and have all callers use return

- lib/FileSystem/fnFsSPIFFS.cpp
- lib/modem/modem.cpp
- lib/network-protocol/TCP.cpp
This adds the missing tcpServer.begin bits, and reverts the change to spiffs config from "flash" to NULL.
> Tcp server and spiffs

- lib/bus/iec/protocol/iecProtocolSerial.cpp
- lib/device/iec/disk.cpp
There are 3 fixes:
* Send all bytes of a file, including the last one
* ATN being asserted immediately after the EOI byte isn't an error, still return the final byte
* ATN being asserted right after acking the EOI byte should not release DATA since interrupt already asserted it
> Fix sending all bytes of file and don't abort if ATN is asserted immediately after EOI

- lib/network-protocol/Protocol.cpp
With this change, writing text data from the ATARI to a remote computer will follow the translation mode established using NTRANS or AUX2. Previously, when transmitting text data from the ATARI, only translation mode 3 (0x9B <--> CRLF) worked successfully.
An edge-case remains:
The Action! cartridge saves its text data with the non-ATARI EOL char = CR. No translation should occur when saving text from Action!.  However if the translation mode were set to 2 or 3 (2=0x9B <--> LF, 3=0x9B <--> CRLF), data is being incorrectly translated from CR --> CRLF even though Action!'s EOL char should not have qualified for translation.
In tracing the issue, I noticed  [that AUX2 = bitwise-OR between the requested translation mode and the existing …
> Improve ATARI EOL translation

- lib/bus/rc2014bus/rc2014bus.cpp
- lib/bus/rc2014bus/rc2014bus.h
- lib/device/rc2014/modem.cpp
- lib/device/rc2014/modem.h
- lib/device/rc2014/network.h
Since we moved to using an SPI bus for RC2014, the modem support had
become unusable. Refactor the the modem to use command frames,
adding a circular buffer to emulate a UART. Code on the RC2014 will
batch characters together to send/receive command frames in the
"driver"
> rc2014: modem: refactor to use command frames

- lib/device/sio/fuji.cpp
This should fix the issue with not saving wifi passwords.
> Remove guard introduced for saving passwords

- lib/device/iec/fuji.cpp
This loop was assuming MAX_DISK_DEVICES = 8, which is not the always the case.
> _fnDisks is declared with MAX_DISK_DEVICES, which changes sizes.

- lib/device/cx16_i2c/fuji.cpp
- lib/device/iec/network.h
- lib/device/iwm/fuji.cpp
- lib/device/rs232/fuji.cpp
- lib/device/rs232/network.cpp
- lib/device/sio/fuji.cpp
- lib/device/sio/network.cpp
- lib/network-protocol/FS.cpp
- lib/network-protocol/Telnet.cpp
- lib/network-protocol/UDP.cpp
cppcheck: (error) Array 'channelMode[15]' accessed at index 15, which is out of bounds. [arrayIndexOutOfBounds] cppcheck: (error) Array '_fnDisks[6]' accessed at index 7, which is out of bounds. [arrayIndexOutOfBounds] cppcheck: (error) Memory leak: newData [memleak]
cppcheck: (error) Memory leak: dataBuf [memleak]
several fopen() with no fclose() fixed
> Fixed cppcheck errors.

- build.sh
For @mozzwald 
run:
```shell
$ ./build.sh -z
```
it will clean, build filesystem, then build with the zip options enabled.
cleans up after itself.
It works by finding the line containing "; post:build_firmwarezip.py" and then inserts the post option ABOVE it.
After building zip, it removes the option it added, leaving the platformio.ini file as it was.
It will fail if there's no line with the comment at the end of the extra_scripts section, so the current template should work.
> Add -z option to build.sh to build firmware zip

- build.sh
- platformio-sample.ini
For @dillera - `build.sh -z` now supported on mac.
This is a small change to use sed in a way that's compatible with Macs version.
> Fix sed calls to work on Mac

- lib/device/rc2014/fuji.cpp
- lib/device/rc2014/fuji.h
The RC2014 does not match the other platforms with the size of the SSID array. Fix this.
> RC2014: fuji: align SSID size with other platforms

- lib/device/rc2014/network.cpp
Remove the need for the N: specifier for opening
the network device.
This is part of the rc2014 library refactoring for the network device.
> RC2014: network: remove need for N: specifier

- lib/device/rc2014/network.cpp
Since we removed the N: prefix from network device specs for RC2014, we missed one usage in rc2014_set_json_query()!
Fix this.
> RC2014: network: fix json query

- lib/device/iwm/disk.cpp
- lib/device/iwm/disk.h
- lib/device/iwm/fuji.cpp
- lib/media/apple/mediaType.h
- lib/media/apple/mediaTypePO.cpp
Tested with 2 machines that having the same disk (CHAMP.LODERUN.HI.img) mounted read-only mode at the same time. 
For this program, it looks like the high score table is read at startup and re-read prior to posting a new score. So the high score table will not be updated during attract mode, but will show recently submitted scores from other machines prior to adding a new entry.
Trivia. Championship Lode Runner tests the disk for its write permission during boot up. If the game is deemed to be write-protected, only the attract mode is displayed. With the high score enabled hackery, the write test passes and the player can start level 1.
> Apple II - high score enabled

- lib/media/apple/mediaType.h
- lib/media/apple/mediaTypePO.cpp
Starting at offset 0x48 of 2mg header:
'H','I',<blk_lbound_lo>,<blk_lbound_hi>,<blk_ubound_lo>,<blk_ubound_hi>
where blk is the block range containing the high score table (or blocks to be written)
range is defined by lower bound and upper bound inclusive
if upper bound is undefined (0x0000), then the lower bound defines a single block range.
> Apple II High Score. Write block range

- lib/device/sio/fuji.cpp
- lib/device/sio/fuji.h
- lib/utils/utils.cpp
- lib/utils/utils.h
This extends command $E8 (get adapter config) to return additional strings for the various IP and MAC values to save the client from having to do it.
> Add extended Adapter Config information

- lib/config/fnc_wifi.cpp
- lib/device/sio/fuji.cpp
- lib/device/sio/fuji.h
- lib/hardware/fnWiFi.cpp
- lib/hardware/fnWiFi.h
This change will first try the given ssid/password combination before saving it to fnconfig.
It works by shutting down the existing wifimanager, starting a new mini version with some blocking code that checks whether a disconnect or connect event happens.
The disconnect tells us the config was bad, and we then stop the saving, and report the error to the host.
If the config was good, the wifi manager is restarted, with a small delay to allow it to connect, and the host is then given a success code, allowing them to then check the wifi status and see everything is good.
I've also (sorry) add the start of the block directory code to this commit as I will be adding it anyway. Nothing calls it, but I kept losing it in between stashing changes.
I've test compiling everything only on Atari …
> Add bad-connection detection to set-ssid

- lib/device/sio/network.cpp
- lib/device/sio/network.h
- lib/fnjson/fnjson.cpp
- lib/fnjson/fnjson.h
See https://github.com/FujiNetWIFI/fujinet-platformio/wiki/N:-SIO-Command-$FB---Set-JSON-Parameters
This allows host to change JSON parameters from the host using ioctl commands:
```cpp
#ifdef BUILD_ATARI
err = network_ioctl(0xFB, 0, 1, ipify_json, 0, 0, 0);    // set json Query Param
err = network_ioctl(0xFB, 1, 0x00, ipify_json, 0, 0, 0);    // set json Line Ending (default is usually 0x9b)
#endif
```
> Add 00 dstats $FB command to change json parameters

- lib/device/iwm/disk.cpp
- lib/device/iwm/disk2.cpp
- lib/media/apple/mediaType.cpp
- lib/media/apple/mediaType.h
- lib/media/apple/mediaTypeDO.cpp
- lib/media/apple/mediaTypeDO.h
- lib/media/apple/mediaTypeDSK.cpp
- lib/media/media.h
For issue #616
- add support for DOS order .DO disk images
- look for ProDOS volume header info inside .DSK image files to detect if they are in DOS order or ProDOS order
> Add .DO support. Look inside .DSK files to detect sector order.

- lib/device/iwm/fuji.cpp
> fix web mount list on apple2

- lib/base64/base64.c
The FN code using this code presumes anyhow that 'os_malloc' is the same as 'malloc'.
> Remove dependency on os.h

- lib/device/iwm/disk.cpp
- lib/device/iwm/disk2.cpp
- lib/device/iwm/disk2.h
- lib/media/apple/mediaTypeDO.cpp
- lib/media/apple/mediaTypeDSK.cpp
- lib/media/apple/mediaTypeDSK.h
- lib/media/apple/mediaTypeWOZ.h
- support 36 and 40 track .DO, .PO, and .DSK files
- check file size is supported size
- plumb MEDIATYPE_UNKNOWN errors in mount code
> apple2: Support 40 track 5.25 inch disk images

- lib/FileSystem/fnFS.cpp
- lib/device/iwm/fuji.cpp
- lib/device/iwm/fuji.h
- check for null after calling host.file_open, which can fail, e.g. if the tnfs times out
- fix mount call to use 140K file size for autorun.po and mount-and-boot.po
> apple2: fix crash when image mount fails

- pico/mac/CMakeLists.txt
- pico/mac/commands.c
- pico/mac/commands.pio
- pico/mac/dcd_commands.pio
- pico/mac/dcd_read.pio
- pico/mac/dcd_write.pio
- pico/mac/enand.pio
- pico/mac/mux.pio
The drive ID is generated by a state machine and pushed to the input FIFO. The FIFO has to be read by the software. The software was only reading the FIFO in the DCD loop; however, with no DCD mounted, the FIFO would fill up cause the PICO to stop. The servicing of the FIFO was moved to the common loop service routine to solve this problem.
> Fix DCD-floppy contention

- lib/slip/ReadResponse.cpp
Add include to fix the following build error:
> add missing <cstddef> include for slip

- lib/device/rc2014/disk.cpp
- lib/device/rc2014/disk.h
- lib/media/rc2014/mediaType.cpp
- lib/media/rc2014/mediaType.h
camelforth requires the size of disk, as it's quite agnostic. Add this command to the Disk device interface.
> rc2014: disk: add command for number of sectors

- distfiles/run-fujinet
`/bin/sh` doesn't support functions - need to use Bash instead.
> fix run-fujinet shebang

- build.sh
On modern arm macs homebrew is installed under `/opt/homebrew`.
```
$ uname -sm
Darwin arm64
$ brew -v
Homebrew 4.2.8
$ which gsed
/opt/homebrew/bin/gsed
```
Also: 
> The --with-default-names option is removed since January 2019
https://stackoverflow.com/a/34815955
Looking for gsed in the path should be the most accurate use of gnu-sed when using homebrew on x86 or arm.
> Better detection of gsed on homebrew.

- lib/network-protocol/FS.cpp
- lib/utils/utils.cpp
Corrected two issues found when using NOS:
1. Unable to open files (such as binary load) from relative path that includes traversing through a parent directory. The logs would show a file open request such as:
Before: `TNFS://my_path/my_sub1/../my_sub2/file.ext`
After: `TNFS://my_path/my_sub2/file.ext`
2. `NCD Nn:` is supposed to clear the mount point. However, sending a null path through the util function to return a canonical path was incorrectly resolving to "/".  A null path now resolves to null.
> Canonical path resolution fixes

- lib/utils/utils.cpp
length > 0 condition is needed to return a null string if a null string was provided as input. But by putting that condition first, it will block the second condition from deriving -1 as an array index.
> Swap conditions, will guard against index out-of-bounds

- lib/device/sio/network.cpp
Tested with both NOS and N-enabled DOS XL. Assumption is other versions use same N-tools wand will behave the same.
> Adjusted sio_set_prefix() to comply with NCD documentation

- include/pinmap/coco_devkitc.h
- lib/bus/drivewire/drivewire.cpp
Read A14/A15 ROM dipswitch via IO36/IO39
> [coco] Set Drivewire BAUD rate based on ROM image selection

- lib/FileSystem/fnFsTNFS.cpp
- lib/TNFSlib/tnfslib.cpp
- lib/TNFSlib/tnfslibMountInfo.h
To connect to a tnfsd server supporting TCP, add `_tcp.` prefix to its hostname, eg.:
```
_tcp.apps.irata.online
```
> Support for TCP protocol in TNFS client.

- lib/FileSystem/fnFsTNFS.cpp
- lib/TNFSlib/tnfslib.cpp
- lib/TNFSlib/tnfslibMountInfo.h
With this PR, the firmware will first try to connect to tnfsd using TCP protocol. If the connection is not possible (tcp/16384 doesn't respond) or the connection is accepted but server doesn't respond to the MOUNT command (because it's an old server version that doesn't handle TCP commands), the client will fallback to UDP.
My suggestion is to wait with merging this PR until these two servers support TCP:
* fujinet.atari8bit.net
* fujinet.pl
I already contacted owners.
> Connect to TCP by default and fallback to UDP.

- lib/bus/drivewire/drivewire.cpp
This resets the system to the configuration disk image.
> Hitting RESET on the CoCo causes an OP_RESET transaction code to occur

- data/webui/template/www/css/core.tmpl.css
- data/webui/template/www/header.tmpl.html
- data/webui/template/www/index.tmpl.html
- data/webui/template/www/restart.html
- lib/http/httpService.cpp
A few responsive updates to CSS and HTML for web UI. The text should now be legible, and buttons and links clickable, without having to zoom in on mobile devices.
- add `<meta name="viewport" content="width=device-width, initial-scale=1.0">` to enable responsive sizing
- move large icons into section headers on small screen sizes
- clean up markup/naming (e.g. change invalid repetition of `id="logowob"` to `class="logowob"`)
This is actual size on an iPhone 12 pro
> webui: make webui mobile-friendly (responsive)

- .github/workflows/nightly.yml
GitHub Action that will build nightly firmware builds & attach them to a pre-existing static Release.
The URL in this PR in lines 77-78 & 87-88 need to be updated for the pre-created Release setup in the `FujiNetWiFi/fujinet-firmware` repo.
Find the URL for the new release at this URL: https://api.github.com/repos/fujinetwifi/fujinet-firmware/releases
Also this permission setting in `Settings -> Actions -> General` will need to be set to allow the Action to upload the assets:
> add nightly builds GHA

- .github/workflows/nightly.yml
Remove the step that attaches the `release*.json` files to the nightly release assets since they aren't useful.
> stop attaching the release.json files

- lib/TNFSlib/tnfslib.cpp
- lib/TNFSlib/tnfslibMountInfo.h
This is required, because the keep-alive timer can interrupt a running transaction and cause unexpected recv() results, which usually breaks the whole session, as in https://github.com/FujiNetWIFI/fujinet-firmware/issues/741.
> Put the TNFS transaction in a mutex.

- README.md
- README_wifi.md
- build-sh.md
I spotted a few typos in the markdown files (readme, build-sh, readme_wifi), so I corrected them :)
> fix typos in documentation markdown

- lib/TNFSlib/tnfslib.cpp
- lib/TNFSlib/tnfslibMountInfo.h
The standard mutex is not reentrant and we use recursive calls to _tnfs_transaction in the session recovery (which will block with std::mutex).
> Use recursive mutex for the transactions.

- fujinet_pc.cmake
- lib/TNFSlib/tnfslib.cpp
- lib/TNFSlib/tnfslibMountInfo.h
- lib/TNFSlib/tnfslib_udp.h
- lib/TNFSlib/tnfslib_udp_testing.cpp
This PR refactors the `_tnfs_transaction()` function, splitting it into smaller units and fixing bugs in the routines responsible for handling invalid responses and sessions recovery. These bugs, described in the #741 are probably the reason why the UDP protocol doesn't work correctly for some FN users.
In the b488003d2625b7ae5d11c867bdf6d1243f9567c8, the large `_tnfs_transaction()` method is split into smaller units. This commit is a pure refactoring and it shouldn't change any behavior of the function. The bug fixes are built on top of it, in the following commits.
The commit a037a53b5f09d3b5e291108f83529c5a82493db6 separates request and response buffers in the `_tnfs_transaction()`. This is required to retry the command - otherwise we wouldn't have the original request that can be send …
> Improve the UDP stability

- .github/workflows/nightly.yml
Fix firmware file output name to something standard so the `deploy-nightly` workflow step can find it when build targets don't match matrix item names.  
Also removed the date stamp from the file name for Andy.
NOTE: need to manually delete the old asset files with the date from the [Nightly Builds](https://github.com/FujiNetWIFI/fujinet-firmware/releases/tag/nightly) Release since the new files will have different names so won't overwrite current ones.
> add step to fix name for upload

- build_firmwarezip.py
Clearly outputs firmware zip file location at the end of a `build.sh -z` run.
Example: 
```
...
makezip([".pio/build/fujiapple-rev0/firmware.bin"], [".pio/build/fujiapple-rev0/firmware.elf"])
Creating firmware zip for FujiNet ESP32 Board: fujinet-v1-8mb
********************************************************************************
*
*   FIRMWARE ZIP CREATED AT: firmware/fujinet-APPLE-v1.3.zip
*
********************************************************************************
```
> clearly output firmware file location

- .github/workflows/nightly.yml
Re-worked the nightly build job to improve the following:
- Requires a variable `RUN_NIGHTLY` to be set to `true` on the GitHub repository (or fork) before the nightly job will run (avoids automatically running/failing on forks)
- Replaces the `WebFreak001/deploy-nightly` action with the `softprops/action-gh-release` which handles both creating the Release/Tag as well as uploading resources so it is no longer necessary to manually create a Release & hard-code the release URL/ID into the workflow
***NOTE:***  In order for this workflow to work once merged it will be necessary to add teh `RUN_NIGHTLY` repository variable to the `FujiNetWIFI/fujinet-firmware` repository & set it to `true`!
These changes should continue to re-use the existing `Nightly Builds` Release but it will be necessary …
> remove manual requirements for nighly build job

- lib/TNFSlib/tnfslib.cpp
This way we'll read all the messages from the buffer until we get the right one.
Before this commit we were sending another request, which would keep the send/recv pair out of sync.
> Try to recv next message if the receive seq is smaller than expected.

- lib/device/sio/network.cpp
Before:
`NCD N1:TNFS://localhost` resolves to `TNFS:/localhost/` (losing the `//` after the protocol)
After
`NCD N1:TNFS://localhost` resolves to `TNFS://localhost/`
As reported in Discord https://discord.com/channels/655893677146636301/925136532959002684/1251354402241904733
> Fix ATARI set_prefix like TNFS://localhost -> TNFS:/localhost/

- lib/FileSystem/fnFsTNFS.cpp
The CoCo repository is replete with directories for each application/game/whatever, and as such being able to filter the directory names as well is helpful.  This commit adds this functionality by adding a trailing `/` to the filter string.
> Added directory filtering when filter pattern ends with `/`

- lib/hardware/fnWiFi.cpp
Re-enable mDNS in Atari build so that the web interface can be accessed at e.g. `http://fujinet.local` without any further configuration.
> [fnWifi] re-enable mdns for Atari

- build_firmwarezip.py
This avoids an edge case where commit messages might contain characters that create invalid JSON and prevent flashing.
**BEFORE**
**AFTER**
> [build] use json.dumps to properly escape firmware release.json

- components/libsmb2/lib/dcerpc.c
- components/libsmb2/lib/init.c
- lib/FileSystem/fnDirCache.cpp
- lib/FileSystem/fnFsLittleFS.cpp
- lib/FileSystem/fnFsSD.cpp
- lib/hardware/fnWiFi.cpp
- lib/http/httpService.cpp
- lib/libssh/src/misc.c
Hi,
due to some misleading warnings during build I propose to remove unused variables and disable warning related to uninitialized structure fields for some source files using #pragma compiler feature;
> unused vars and undefined structure fields

- .github/workflows/platformio.release-MASTERIES-REVA-SPIFIX.ini
- include/pinmap/a2_rev0.h
- lib/bus/iwm/iwm_ll.cpp
- lib/bus/mac/mac_ll.cpp
- lib/device/iwm/cpm.cpp
- lib/hardware/fnSystem.cpp
- lib/hardware/fnSystem.h
- platformio-sample.ini
This renames a couple of pin constants so they better reflect what they represent. SP_RDDATA is now the pin that will be controlled by SPI & RMT and SP_RD_BUFFER is the pin that is used to enable/disable the buffer chip on older FujiNet Apple II revisions.
> Change SP_RDDATA to be the GPIO pin that is connected to the Disk II.

- lib/device/sio/fuji.cpp
- lib/device/sio/fuji.h
Modified following files to _**not**_ use PSRAM functions to allocate memory when building for the fujinet-pc for ATARI.
- `lib/device/sio/fuji.cpp`
- `lib/device/sio/fuji.h`
> Adjusted malloc for PC build for ATARI

- lib/device/sio/fuji.cpp
In `lib/device/sio/fuji.cpp`:
- Added error message in constructor if request for memory was unsuccessful.
- Altered the `sioFuji` destructor to:
- call the `sioNetwork` destuctor for each assigned element in the `sioNetDevs` array.
-  use `heap_caps_free()` for ESP and `free()` for PC to release memory.
> Adjusted memory management in sio sioFuji class

- lib/bus/iwm/iwm.cpp
- lib/bus/iwm/iwm.h
- lib/bus/iwm/iwm_ll.cpp
- lib/device/iwm/disk.cpp
- lib/device/iwm/disk2.h
- lib/device/iwm/fuji.cpp
- lib/device/iwm/fuji.h
- lib/http/httpService.cpp
Remove direct access to `_fnDisk2s` to eliminate shadowing issues with `_fnDisks.disk_dev` and ensure more consistent access. This is necessary to allow config settings (such as write enabled) to pass through to the object that is actually being used to contain the disk image.
Changing `DEVICE_TYPE` to be a pointer seems like a "more correct" change but that would have required changing far too many things.
> Remove direct access to _fnDisk2s

- lib/bus/iwm/iwm.cpp
- lib/bus/iwm/iwm.h
Split up service() into sub services to make it easier to add more services (such as Disk II write).
> Split up service() into sub services

- build-platforms/platformio-fujinet-foenix-lolin-d32-dw.ini
- data/webui/config/fujinet-foenix-lolin-d32-dw.yaml
- include/pinmap.h
- include/pinmap/foenix_os9_d32pro.h
- platformio-sample.ini
Adding in some platform and pinmap configs in the builds for Foenix retro computer using the D32 Lolin.
Build board remains COCO w/ drivewire.
SD card reading works again, so reading wifi config works.
> Add build platforms and pin maps for Foenix comptuer using D32

- data/webui/config/fujinet-foenix-lolin-d32-dw.yaml
- lib/hardware/fnUART.cpp
- platformio-sample.ini
following advice of team members i'm using the PINMAP definition of the D32 on the Foenix hardware to stop fnuart.cpp from inverting the tx and rx lines for the FN. This works and now the devices are communicating with logs. It's not completely mounting and reading the disk yet but on it's way.
> [dw][foenix] fix board by not inverting tx rx in fnuart2

- lib/ftp/fnFTP.cpp
Adds small check to FTP lib to skip trying to send a password if server doesn't require one, i.e. server returns `230` in response to initial login call.
> fnFTP: skip sending password if server didn't 331

- lib/hardware/fnHardwareTimer.cpp
- lib/hardware/fnHardwareTimer.h
Testing has proven 771 is the cause of SmartPort unreliability.
Tested revert with tnfs://ayce.fozztexx.com/SmartPort.Exorciser.po
> Revert "Update fnHardwareTimer to use driver/gptimer.h"

- lib/utils/peoples_url_parser.cpp
- lib/utils/utils.cpp
These changes were inspired by issues found in ATARI NOS when trying to open, launch, copy files using relative paths.
- Fixed a bug in function `util_get_canonical_path`
- Previous logic always exited with trailing slash, not good if input ends with a filename. If trailing slash found in input, then it will exist in output. If not then no slash in output.
- Corrected mistake with condition involving C++ string length.
- Renamed input arg from `prefix` to `path` throughout.
- In peoples_url_parser, added call to `util_get_canonical_path` in place of an existing string replace function that substituted '//' with '/'. This should resolve relative paths in general for all protocols.
> Improve relative path resolution (retry)

- lib/device/sio/network.cpp
Add trailing slash in `lib/device/sio/network.cpp` in method `sio_set_prefix` to `prefixSpec_str`.
Later, adding trailing slash to `prefix` is no longer necessary as it already exists in `prefixSpec_str`.
> ATARI: Improve trailing slash in sio_set_prefix

- lib/bus/iwm/iwm.cpp
- lib/bus/iwm/iwm.h
- lib/bus/iwm/iwm_ll.h
- lib/device/iwm/fuji.cpp
Added a SmartPort STATUS and CONTROL command which allows CONFIG to see which /DRIVEn lines are connected to the FujiNet.
New `IWM_CTRL_CLEAR_ENSEEN` and `IWM_STATUS_ENSEEN` are both defined as `0x08` since it was available. Not sure if it should be a different value, but seems like both should be identical.
CLEAR will reset the "sticky" variable `d2_enable_seen` to 0x00. After that whenever a Disk II enable is seen the appropriate bit will be set in `d2_enable_seen` (bit 0 is drive 1, bit 1 is drive 2). STATUS will fetch the current value so that CONFIG can determine if FujiNet saw the drive access.
This change is for use with the change on CONFIG, see the diskii_drive_detect PR there. https://github.com/FujiNetWIFI/fujinet-config/pull/101
> Added SmartPort STATUS and CONTROL commands to monitor Disk II

- .gitignore
- create-platformio-ini.py
- debug_version.py
- include/version.h
Add debug_version.py to put commit ID into FN_VERSION_FULL during build without altering include/version.h
> Developer tool to put commit ID into FN_VERSION_FULL

- lib/device/sio/network.cpp
Fix to a bug I introduced in a previous change. 
NCD N1:  (by itself is intended to clear the prefix, but was setting the prefix  to '/')
> ATARI: Corrected 'NCD N1:' to clear prefix

- debug_version.py
Change debug_version.py defaults to not use most recent modified date since it causes everything to rebuild.
> Change debug_version.py to not use most recent modified date

- lib/device/sio/fuji.cpp
- lib/http/httpService.cpp
- lib/http/httpService.h
- lib/http/mgHttpService.cpp
Adds a simple URL shortener to the webserver, primarily for use with the new QR code encoding feature.
You are pretty limited in the amount of data you can encode in a QR code if it can only be 21x21, and this may be too short for many URLs. This URL shortener allows you to take an arbitrarily long URL and shorten to `http://{fujinet_ip}/url/{id}`.
For Atari, you can tell the QR encoder to shorten the supplied URL first by setting bit 4 on AUX2 (i.e. adding 16 to the desired error correction level).
> URL shortener

- lib/http/mgHttpService.cpp
Fixes issue with building FujiNet-PC on Ubuntu/Windows due to omitting include
> [PC] fix: include <algorithm> header

- include/pinmap/esp32s3-wroom-1.h
- lib/device/sio/voice.cpp
- lib/device/sio/voice.h
- lib/sam/sam.c
- lib/sam/sam.h
- lib/sam/samlib.cpp
For Sam : 
- Add command for change presets
- Fixed "Reset" command.
For ESP32-S3 : 
- Add Analogic Audio Out
- Add I2S Audio Out if add "-D ESP32S3_I2S_OUT" on build_flags
- Added a command to activate or not the I2S Out
> Device ESP32-S3 : Add Analogic & I2s Audio Out

- lib/network-protocol/FS.cpp
- lib/network-protocol/Protocol.cpp
- lib/network-protocol/Protocol.h
Mode 0x0c (12) read/write was returning EOF when writing to the end of file.
Code was added to flag this, and to return a successful error if the write is successful.
Mode 0x0c (12) was also returning 0 bytes available for any file that had existing data. This was because the file was not stat() and filesize() had not been adjusted. 
There is still a potential for reading and writing within the same file to cause a file size change, however, this will not come into play until seeking and telling (NOTE/POINT) are actually implemented in FS.
> [network-protocol] do not emit EOF on write.

- lib/printer-emulator/atari_1025.cpp
- lib/printer-emulator/atari_1027.cpp
- lib/printer-emulator/atari_1029.cpp
- lib/printer-emulator/atari_820.cpp
- lib/printer-emulator/atari_822.cpp
- lib/printer-emulator/atari_825.cpp
- lib/printer-emulator/atari_xdm121.cpp
- lib/printer-emulator/atari_xmm801.cpp
- lib/printer-emulator/epson_80.cpp
For PDF printers that support form feed, eject the current page, create the next one.
> Fix printer emulator form feed

- lib/http/httpServiceBrowser.cpp
- lib/http/httpServiceBrowser.h
Before this commit it's possible to escape the configured root by specifying `..` between the URL-encoded slash: `%2F`:
```
http://localhost:8000/browse/host/1/%2F..%2F..%2F..%2F
```
> Validate the path in Fujinet "hosts list" browser in the web UI.

- lib/device/rs232/disk.cpp
- lib/device/rs232/fuji.cpp
Fix compile time errors due to mis-matched formats in debug output functions.
> fix uint32 compile errors

- lib/device/sio/fuji.cpp
- lib/device/sio/fuji.h
- lib/http/httpService.cpp
- lib/http/httpService.h
- lib/http/mgHttpService.cpp
Adds `/hosts` endpoint(s) to web server. Primarily for use with "Send to FujiNet" browser extension.
```sh
GET /hosts
SD
fujinet.online
apps.irata.online
fujinet.diller.org
https://bocianu.atari.pl
atarionline.eu
fujinet.pl
tnfs.abbuc.social
```
```sh
POST /hosts?hostslot=7&hostname=tnfs.example.com
SD
fujinet.online
apps.irata.online
fujinet.diller.org
https://bocianu.atari.pl
atarionline.eu
fujinet.pl
tnfs.example.com
```
> [webui] add /hosts endpoint for view/updating host slots 

- data/webui/template/www/index.tmpl.html
- data/webui/template/www/js/settings.tmpl.js
- lib/device/sio/fuji.cpp
- Adds a little `[EDIT]` link next to host slots
- Ensures host names get updated when endpoint is called
> [webui] add edit button to host slots

- lib/device/adamnet/fuji.cpp
- lib/device/comlynx/fuji.cpp
- lib/device/cx16_i2c/fuji.cpp
- lib/device/drivewire/fuji.cpp
- lib/device/h89/fuji.cpp
- lib/device/iec/fuji.cpp
- lib/device/iwm/fuji.cpp
- lib/device/mac/fuji.cpp
- lib/device/new/fuji.cpp
- lib/device/rc2014/fuji.cpp
- lib/device/rs232/fuji.cpp
- lib/device/s100spi/fuji.cpp
when updating slot hostname (from webui), also call `_populate_config_from_slots` so the updated name gets copied over there as well
> [fuji] set_slot_hostname: repopulate config

- lib/device/sio/fuji.cpp
- lib/qrcode/qrmanager.cpp
- lib/qrcode/qrmanager.h
- fix bug where output formats other than bytes wouldn't work after the 1st encode in atari implementation
- new "bitmap" output option for QR encoder, that outputs things in MSB->LSB order suitable to copy directly into e.g. sprite data
- renamed `QR_OUTPUT_MODE_BITS` to `QR_OUTPUT_MODE_BINARY` and `::to_bits` to `::to_binary` to make less confusing(?) with new bitmap mode
> QR: new bitmap output + fix

- lib/device/sio/fuji.cpp
- lib/qrcode/qrcode.c
- lib/qrcode/qrmanager.cpp
The underlying QR generation library silently generates invalid QR codes if the input text exceeds the capacity for the given size/error correction level.
Unfortunately there's no straightforward formula for calculating capacity, so this uses a table to validate and returns an error if not. Also adds checking for version and error correction level parameters. For Atari implementation, an SIO error is generated in this case.
> [qr] validate params; error if input > capacity

- lib/device/sio/fuji.cpp
Fixes edge case where after QR encoding fails, subsequent attempts also fail
> [qr] fix: always clear in buf even if encode fails

- lib/FileSystem/fnFsTNFS.cpp
- lib/TNFSlib/tnfslib.h
- lib/utils/utils.cpp
There are 2 features here:
1. Filtering pattern starting with `!` will be transformed into `**/pattern*`, required by the new tnfsd TNFS_DIROPT_TRAVERSE option (see https://github.com/FujiNetWIFI/tnfsd/pull/16)
2. Add long-path support for `util_ellipsize()` (see below).
Before this PR, the `util_ellipsize()` removes the middle part of the string, replacing it with `...`, to fit into the specified `dstsize`. After this PR, the function checks if the specified string is a long path (and contains slash in the middle). If that's the case, it'll try to return the full basename of the file + as much as the parent path as possible, e.g.:
```
games/s/spy vs spy 2/spy vs spy 2.atr
```
will be translated into:
```
...spy 2/spy vs spy 2.atr
```
If the basename doesn't fit into the specified size, …
> Support recursive filtering in TNFS.

- lib/utils/peoples_url_parser.cpp
- lib/utils/peoples_url_parser.h
Fixed issues discovered in PeoplesUrlParser:
- parsing path, separating query and fragment
- base_name - only last ext is removed
- parsing url without a schema
(changes here are not addressing need for proper URL encoding)
Example result:
```
mRawUrl: http://user@host:port/dir1/dir2/dir3/file.ext1.ext2.ext3?a=1&b=2#sec
url:     http://user@host:port/dir1/dir2/dir3/file.ext1.ext2.ext3?a=1&b=2#sec
scheme: http
user pass: user -- 
host port: host -- port
path: /dir1/dir2/dir3/file.ext1.ext2.ext3
pathToFile: /dir1/dir2/dir3/
name: file.ext1.ext2.ext3
base_name: file.ext1.ext2
extension: ext3
root: http://user@host:port
base: http://user@host:port/dir1/dir2/dir3/
query: a=1&b=2
fragment: sec
```
> [url parser] attempt to fix string splitter

- data/webui/template/www/index.tmpl.html
- lib/FileSystem/fnDirCache.cpp
- lib/FileSystem/fnDirCache.h
- lib/FileSystem/fnFsHTTP.cpp
- lib/device/drivewire/fuji.cpp
- lib/device/drivewire/network.cpp
- lib/utils/peoples_url_parser.cpp
[coco] fuji device: check nullptr on disk image open
- check for nullptr on disk image open
- set errorCode on file (disk image) open
- set errorCode on dir open
[coco] network device open - deviceSpec from null terminated string
url parser: properly set base_name if there is no extension
[HTTP FS] fix dir_open
- use proper buffer size (COPY_BLK_SIZE) when reading data from HTTP client
- fix file size parsing
- make sure the directory url ends with '/' to avoid unnecessary redirect
fnDirCache - use pointers for sorted entries
- no need to copy directory entries when sorting/filtering
[PC] WebUI - one restart button is enough
> Few small fixes

- lib/bus/iwm/iwm.cpp
- lib/bus/iwm/iwm.h
- lib/bus/iwm/iwm_ll.cpp
- lib/bus/iwm/iwm_ll.h
Fixes https://github.com/FujiNetWIFI/fujinet-firmware/issues/884 and https://github.com/FujiNetWIFI/fujinet-firmware/issues/882
Pointed to v1.5-rc this time. But you better double check me!
> allow ::start() to be called before ::stop() so that it can be used to change drives #886

- lib/bus/iwm/iwm_ll.cpp
> Prevent divide by zero error when switching to a track of zero length.

- lib/bus/iwm/iwm_ll.cpp
- lib/bus/iwm/iwm_ll.h
- lib/device/iwm/disk2.h
I can't find anything that calls these functions. This code appears to be dead. Especially since in disk2.h `disableD2()` calls `diskii_xface.enableD2()` which seems entirely backwards.
> Remove what appears to be dead code for disabling Disk II drive 2

- .github/workflows/release.yml
Fixes error when moving firmware file after build.
Allows manual running of the release build by specifying tag name
> Allow auto or manual run of release build & fix mv error

- components_pc/mongoose/mongoose.c
- components_pc/mongoose/mongoose.h
- lib/http/mgHttpClient.cpp
- lib/http/mgHttpClient.h
- lib/network-protocol/HTTP.cpp
- process the response parts when data arrives,
- do not wait for the entire response (MG_EV_HTTP_MSG event)
- replace mg_http_connect() with mg_connect()
- use MG_EV_READ event to handle all incoming data
- allow responses larger than mongoose buffer limit (3MB)
- change protocol to HTTP/1.1
- support for chunked transfer encoding
- add _perform_fetch() to fetch the response in parts
- implement PROPFIND method
- handle HEAD, MKCOL COPY and MOVE methods
- fix mongoose TLS buffer overflow (back-ported)
> [PC] Refactor FujiNet-PC HTTP client (rebased)

- include/debug.h
- include/pinmap/rs232_s3.h
- lib/hardware/fnSystem.cpp
- lib/hardware/keys.cpp
for upcoming RS232-REV1 hardware using ESP32-S3:
* Fix inverted SD Card detect pin
* Use printf for debug output so it's sent over USB instead of UART
* Enable button A for RS232
* GPIO pinmap updates/fixes
> rs232-s3: fix sdcard detect, send debug output to usb, enable button A, pinmap fixes

- lib/hardware/fnSystem.cpp
With some bits in fnSystem getting shuffled around, Adam no longer had the call to setup_card_detect() to handle resetting or mounting the SD card upon insertion/removal.
> [adam][fnSystem] fixes #914 - ensure setup_card_detect() is run.

- lib/bus/cx16_i2c/cx16_i2c.h
- lib/bus/rc2014bus/rc2014bus.h
- lib/device/cx16_i2c/fuji.cpp
- lib/device/iwm/disk.cpp
- lib/device/mac/fuji.cpp
- lib/device/rs232/apetime.cpp
- lib/device/rs232/disk.h
- lib/hardware/Esp.cpp
- lib/meatloaf/meat_media.h
- lib/media/adam/mediaTypeDDP.cpp
- lib/media/adam/mediaTypeDSK.cpp
- lib/media/h89/mediaTypeIMG.cpp
- lib/media/rc2014/mediaTypeIMG.cpp
- lib/media/s100spi/mediaTypeDSK.cpp
- platformio-ini-files/platformio.common.ini
- platformio-sample.ini
Changes needed to compile for v6.10.  Needs to be tested on all platforms.
This PR is without the changes to components.
> Bring things up to date with platform-espressif32 v6.10.0 (2nd try)

- .github/workflows/nightly.yml
Fix for
https://github.com/softprops/action-gh-release/issues/628
> nightly build: use newer softprops/action-gh-release to fix build crash

- lib/hardware/fnHardwareTimer.cpp
- lib/hardware/fnHardwareTimer.h
Isolate timer headers to fnHardwareTimer.cpp to reduce number of warnings printed during compile.
> Isolate timer headers to fnHardwareTimer.cpp

- build_firmwarezip.py
This adds the new `update.bin` partition to the firmware zip builder JSON output and adjusts the partition offsets accordingly. It temporarily creates `update.bin` with all zeros until we can add the correct [mlff](https://github.com/idolpx/mlff) from @idolpx .
> Fix firmware zip builder for new partition layout

- lib/device/iwm/fuji.cpp
Removed the `#ifdef ESP_PLATFORM` and simplified the method so that it does the same thing on both ESP32 and "PC".
Opened in draft mode, needs testing on both Apple II and FujiNet PC Apple II emulation.
> Simplify insert_boot_device() in iwm/fuji.cpp

- build.sh
My take on automatically activating the PlatformIO Python virtual env when using `build.sh`.
> add functionality to auto-activate venv

- build.sh
Fixed the output message to be more accurate if the PIO `penv` has already been activated in the current environment.  
Activating venv (penv directory exists & isn't already activated): 
Activation failed with a bogus or missing PIO penv directory - script continues without it: 
`$VIRTUAL_ENV` is already set to the PIO penv so just continues without doing anything:
> Fix PIO venv activate message output

- .clang-format
- .dir-locals.el
- .github/workflows/check-formatting.yml
- .github/workflows/coding-standard-requirements.txt
- coding-standard.py
Much of this came about while I've been working on converting the fuji device to a unified class hierarchy with inheritance. I needed a way to format the methods identically to make it easier to diff them. I expanded it to use as a pre-commit hook, then expanded it further so it can work as a PR check.
The Python script will check text files to make sure they don't have any tab characters (except Makefiles) and they don't have trailing whitespace. I made it smarter than git's sample pre-commit hook: it *only checks the files that are being changed*, not the entire repo. This way there's no huge commit just to update whitespace.
It's also able to do double duty as a PR check. Same thing, it only checks the files in the PR, not the entire repo. If there's any bad whitespace then it blocks …
> Created coding-standard.py to check whitespace/formatting of plain text files

- lib/compat/linux_termios2.h
On arch, BOTHER is now defined in glibc:
```shell
❯ grep BOTHER /usr/include/bits/*.h
/usr/include/bits/termios-cbaud.h:#define  __BOTHER    0010000
/usr/include/bits/termios.h:# define BOTHER  __BOTHER
```
The original guard around termios2 struct is now skipped because BOTHER was the control for it.
glibc does not define it anywhere in linux, it's in kernel headers, but we don't include those for obvious reasons.
This PR amends the guards to separate each part that's defined, but allows termios2 struct to be defined.
A good hard look at why we do any of this shit is probably required of the whole uart classes code.
> Fix termios2.h BOTHER compile issue with fujinet-pc

- lib/device/iwm/fuji.cpp
This reverts commit 76b76fa7b50d395f55944e7b9090911618fddc01.
Fixes #910
> Must set readonly *after* mount() resets the readonly flag

- lib/qrcode/qrcode.c
- lib/qrcode/qrcode.h
- lib/qrcode/qrmanager.cpp
- lib/qrcode/qrmanager.h
minor tweaks to qrManager::to_petscii()
Now if you set version to "0" when calling QRManager::encode(), it will automatically select the minimum version to fit your data.
> add qrcode_minVersion() to auto size generated qrcode

- lib/device/adamnet/keyboard.cpp
- lib/device/adamnet/modem.cpp
- lib/device/comlynx/keyboard.cpp
- lib/device/comlynx/modem.cpp
- lib/device/drivewire/modem.cpp
- lib/device/h89/modem.cpp
- lib/device/iwm/modem.cpp
- lib/device/mac/modem.cpp
- lib/device/new/keyboard.cpp
- lib/device/new/modem.cpp
- lib/device/new/serial.cpp
- lib/device/rc2014/modem.cpp
- lib/device/rs232/modem.cpp
- lib/device/s100spi/modem.cpp
- lib/device/sio/modem.cpp
- lib/network-protocol/TCP.cpp
- lib/tcpip/fnTcpServer.cpp
- lib/tcpip/fnTcpServer.h
The available() method should return the number of bytes available to be read to be consistent with the rest of FujiNet. It returns fnTcpClient so it makes more sense to call it client().
> Rename fnTcpServer::available() to fnTcpServer::client()
